/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as TestesRouteImport } from './routes/testes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evolucao': typeof EvolucaoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/testes': typeof TestesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evolucao': typeof EvolucaoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/testes': typeof TestesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evolucao': typeof EvolucaoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/testes': typeof TestesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evolucao' | '/perfil' | '/plano' | '/testes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evolucao' | '/perfil' | '/plano' | '/testes'
  id: '__root__' | '/' | '/evolucao' | '/perfil' | '/plano' | '/testes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvolucaoRoute: typeof EvolucaoRoute
  PerfilRoute: typeof PerfilRoute
  PlanoRoute: typeof PlanoRoute
  TestesRoute: typeof TestesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvolucaoRoute: EvolucaoRoute,
  PerfilRoute: PerfilRoute,
  PlanoRoute: PlanoRoute,
  TestesRoute: TestesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
